// <auto-generated />
namespace DaleelElkheir.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addWhoAreTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addWhoAreTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201902242207054_addWhoAreTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
